"""add category table and habit.category_id

Revision ID: 712059f08f48
Revises: b912c7084ed8
Create Date: 2026-09-16 16:44:31.438053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712059f08f48'
down_revision: Union[str, Sequence[str], None] = 'b912c7084ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('habit', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'habit', 'category', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'habit', type_='foreignkey')
    op.drop_column('habit', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
