"""create neutralized day table

Revision ID: b912c7084ed8
Revises: c7b7965a38ec
Create Date: 2026-09-16 11:51:24.400792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b912c7084ed8'
down_revision: Union[str, Sequence[str], None] = 'c7b7965a38ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neutralized_day',
    sa.Column('logical_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('logical_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('neutralized_day')
    # ### end Alembic commands ###
