"""create completion table

Revision ID: c7b7965a38ec
Revises: d012fe12a094
Create Date: 2026-09-16 10:24:06.180767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b7965a38ec'
down_revision: Union[str, Sequence[str], None] = 'd012fe12a094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('logical_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_completion_habit_id_logical_date', 'completion', ['habit_id', 'logical_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_completion_habit_id_logical_date', table_name='completion')
    op.drop_table('completion')
    # ### end Alembic commands ###
