"""create habit table

Revision ID: d012fe12a094
Revises: 
Create Date: 2026-09-16 00:35:34.268872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd012fe12a094'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('BINARY', 'QUANTIFIED', name='habit_kind'), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('period_scope', sa.Enum('DAY', 'WEEK', 'MONTH', 'YEAR', name='period_scope'), nullable=False),
    sa.Column('cadence', sa.Integer(), nullable=False),
    sa.Column('target', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('direction', sa.Enum('AT_LEAST', 'AT_MOST', name='direction'), nullable=False),
    sa.Column('is_essential', sa.Boolean(), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit')
    # ### end Alembic commands ###
